# Base configs
baseurl: "https://pan-user31.github.io/lulu/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "大嚕來襲"
subtitle: "2022.08.26 著陸地球"
author: "pan-user31"
header:
 title: "Photography"
 subtitle: "by Ram Patra"
footer:
 name: "大家好, 我是以芯, 剛誕生到這世界上"
 bio: "我目前喝過四種奶粉, 只穿滿意寶寶, 熱愛聽鋼琴、Jazz, 現在的興趣是踢腿跟吐奶嘴, 人生目前最難的課題是吃飯跟睡覺~ <br/> 總之, 很高興認識你？"
 github: ""
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
