# Base configs
baseurl: "https://pan-user31.github.io/lulu/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "大嚕來襲"
subtitle: "2022.08.26 著陸地球"
author: "pan-user31"
header:
 title: "BABY"
 subtitle: "by Robert and Millie"
footer:
 name: "大家好, 我是潘以芯, 剛誕生到這世界上"
 bio: "我目前是嬰兒室頭髮最茂密的嬰, 熱愛讓爸媽幫我水洗屁屁, 喝奶要配爵士樂和鋼琴, 現在的興趣是掙脫包巾跟吐奶嘴, 人生目前最難的課題是吃飯跟睡覺~ 爸爸媽媽為了我少了很多社交活動, 等我適應地球生活後, 大家要約我們一家三口一起玩唷 :D <br/> 總之, 很高興認識你？"
 github: ""
web_design: "AJ"
social_urls:
  facebook: ""
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
